# name: "Docker Actions"

# on: [push]

# jobs:
#   action:
#     runs-on: "ubuntu-latest"
#     steps:
#       - uses: actions/checkout@v1

#       - name: "hello-action"
#         uses: ./.github/actions/hello-world
#         with:sitory. As you can imagine, this generates a lot of noise when learning.


#           firstGreeting: "Learning Lab User"
